# Generated by Django 3.2 on 2021-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='in_groups',
            field=models.ManyToManyField(blank=True, null=True, to='core.Group'),
        ),
    ]
